### ISSUE TITLE
Could not resolve hostname gitlab.internal.tinyprints.com

### ISSUE THREAD

**Issue by kevkha** [briandowns/raceway#1]
Thanks for sharing this project. This command no longer working

<code>git clone git@gitlab.internal.tinyprints.com:bdowns/raceway.git</code>

``` bash
ssh: Could not resolve hostname gitlab.internal.tinyprints.com: Name or service not known
fatal: Could not read from remote repository.
```

Also, path in main.go should be updated too.

Thanks in advance.

**Comment by briandowns** [comment]
Resolved however this is still a WIP and I haven't worked on it in awhile so I'd have to review to see the current state.  That being the case, I can't guarantee it even still works.  Just an FYI.  Feel free to contribute!  If I know people are using it, I'll most likely continue developing.

**Comment by kevkha** [comment]
Thanks for your prompted response. I think this works better for most users
<code>git clone http://github.com/briandowns/raceway.git</code>
or
<code>git clone https://github.com/briandowns/raceway.git</code>

**Comment by briandowns** [comment]
No prob.  I'm never usually too far from a computer.  Let me know if there's anything else I can do.  Please feel free to submit PR's if you'd like!

**Comment by kevkha** [comment]
Sure. I will after getting the project running successfully first. I attempted to run but getting a load of errors. Am I still missing something? I got mariadb (fomerly mysql) and rally installed and configured successfully on my host already. Besides that I also ran this `go get github.com/go-sql-driver/mysql`

``` bash
myhost:~/repos/raceway # go run main.go scenarios.go scheduler.go config.go
main.go:9:2: cannot find package "code.google.com/p/go-uuid/uuid" in any of:
        /usr/lib64/go/src/code.google.com/p/go-uuid/uuid (from $GOROOT)
        /root/go-projects/src/code.google.com/p/go-uuid/uuid (from $GOPATH)
scheduler.go:19:2: cannot find package "github.com/boltdb/bolt" in any of:
        /usr/lib64/go/src/github.com/boltdb/bolt (from $GOROOT)
        /root/go-projects/src/github.com/boltdb/bolt (from $GOPATH)
main.go:17:2: cannot find package "github.com/briandowns/raceway/database" in any of:
        /usr/lib64/go/src/github.com/briandowns/raceway/database (from $GOROOT)
        /root/go-projects/src/github.com/briandowns/raceway/database (from $GOPATH)
main.go:11:2: cannot find package "github.com/codegangsta/negroni" in any of:
        /usr/lib64/go/src/github.com/codegangsta/negroni (from $GOROOT)
        /root/go-projects/src/github.com/codegangsta/negroni (from $GOPATH)
main.go:12:2: cannot find package "github.com/goincremental/negroni-sessions" in any of:
        /usr/lib64/go/src/github.com/goincremental/negroni-sessions (from $GOROOT)
        /root/go-projects/src/github.com/goincremental/negroni-sessions (from $GOPATH)
main.go:13:2: cannot find package "github.com/goincremental/negroni-sessions/cookiestore" in any of:
        /usr/lib64/go/src/github.com/goincremental/negroni-sessions/cookiestore (from $GOROOT)
        /root/go-projects/src/github.com/goincremental/negroni-sessions/cookiestore (from $GOPATH)
main.go:14:2: cannot find package "github.com/gorilla/mux" in any of:
        /usr/lib64/go/src/github.com/gorilla/mux (from $GOROOT)
        /root/go-projects/src/github.com/gorilla/mux (from $GOPATH)
scheduler.go:20:2: cannot find package "github.com/robfig/cron" in any of:
        /usr/lib64/go/src/github.com/robfig/cron (from $GOROOT)
        /root/go-projects/src/github.com/robfig/cron (from $GOPATH)
main.go:15:2: cannot find package "github.com/unrolled/render" in any of:
        /usr/lib64/go/src/github.com/unrolled/render (from $GOROOT)
        /root/go-projects/src/github.com/unrolled/render (from $GOPATH)
```

**Comment by briandowns** [comment]
Like I said, I haven't done active development on it for a few months and I don't remember it's state as I left it.  I'll have to go through and see where it is before I can give an actual assessment.

**Comment by briandowns** [comment]
From the looks of the "cannot find package" messages, you'll need to "go get" those.

**Comment by kevkha** [comment]
Yep. You were right. I will update and create PR with details. Btw `https://code.google.com/archive/p/go-uuid/` has moved to `github.com/pborman/uuid`. I will go through them and update all if changed. Thanks again.

**Comment by briandowns** [comment]
Another FYI. This project isn't complete and I'm sure how long it'll take to complete as I don't know what else I need to do.

**Comment by kevkha** [comment]
Your TODO's look pretty good. Once I have it up and running I will see which areas need improvement.
I'm close to get it up and running. My DB runs on port 3306 as shown

``` bash
# netstat -nlp | grep mysql
tcp        0      0 0.0.0.0:3306            0.0.0.0:*               LISTEN      26893/mysqld
unix  2      [ ACC ]     STREAM     LISTENING     3939330 26893/mysqld        /var/run/mysql/mysql.sock
```

I've changed the port `3306` in both `config.json` and `database/database.go` but it keeps trying to connect to `3307` like

``` bash
# go run main.go scenarios.go scheduler.go config.go
2016/03/02 18:41:52 dial tcp 127.0.0.1:3307: getsockopt: connection refused
exit status 1
```

Any ideas?

**Comment by kevkha** [comment]
I still couldn't figure it out regarding port `3307` even though I've updated the two mentioned files. Perhaps Go has cached it somewhere.
My workaround now is running mysql on port `3307` by modifying `/etc/my.cnf` and bounce mysql daemon.

``` bash
# netstat -nlp | grep mysql
tcp        0      0 0.0.0.0:3307            0.0.0.0:*               LISTEN      30224/mysqld
unix  2      [ ACC ]     STREAM     LISTENING     3980498 30224/mysqld        /var/run/mysql/mysql.sock
myhost:~/repos/raceway # go run main.go scenarios.go scheduler.go config.go
[negroni] listening on :9999
```

**Comment by briandowns** [comment]
I had a number of different MySQL instances running on my development host which was the cause for the use of port 3306.  You can choose to run your local environment however you want.  If you're having a problem connecting, I'd suggest looking at the MySQL use setup to make sure it's able to connect with the same parameters.

**Comment by kevkha** [comment]
I have only one MySQL instance running on port `3306` and have updated raceway to use this port but it always connecting to port `3307`. Strange.

**Comment by briandowns** [comment]
A quck search a second ago has yielded this: https://github.com/briandowns/raceway/blob/325f6cb0d4e65f7c797dbc80337fec280f19dfff/database/database.go#L12

I'd guess this is your culprit.

**Comment by kevkha** [comment]
I figured it out. I only updated `database.go` in my repos directory (where I did the `git clone` of raceway). Earlier I had to run `go get github.com/briandowns/raceway/database` which installed to `GOPATH=$HOME/go_workspace` so I need to update `database.go` in `GOPATH` too. All is well now. Thanks.

**Comment by kevkha** [comment]
I think best solution is passing the `port` variable to `database.go` that is configured from both `config.go` and `config.json`. I will test it out and create PR.

**Comment by briandowns** [comment]
That was the intent. Another example of how you f this project is in terms of completeness. Again, please don't have expectation of this working or being close to done.
